package com.carcosadreaming.rpg.demographics;

import lombok.Data;

@Data
public class TradeSupportValues
{
  private SupportValue[] sv = {
      new SupportValue( "Alchemist", 1000, 0, true ),
      new SupportValue( "Apothecary", 1000, 0, true ),
      new SupportValue( "Armorsmiths", 3000, 2, false ),
      new SupportValue( "Bakers", 800, 0, true ),
      new SupportValue( "Barbers", 350, 0, true ),
      new SupportValue( "Bathers", 1900, 0, true ),
      new SupportValue( "Beer-sellers", 1400, 0, true ),
      new SupportValue( "Blacksmiths", 1500, 0, true ),
      new SupportValue( "Bleachers", 2100, 0, true ),
      new SupportValue( "Bookbinders", 3000, 0, true ),
      new SupportValue( "Booksellers", 6300, 0, true ),
      new SupportValue( "Buckle Makers", 1400, 0, true ),
      new SupportValue( "Butchers", 1200, 0, true ),
      new SupportValue( "Carpenters", 550, 0, true ),
      new SupportValue( "Chandlers", 700, 0, true ),
      new SupportValue( "Chicken Butchers", 1000, 0, true ),
      new SupportValue( "Coopers", 700, 0, true ),
      new SupportValue( "Copyists", 2000, 0, true ),
      new SupportValue( "Cutlers", 2300, 0, true ),
      new SupportValue( "Doctors", 1700, 8, false ),
      new SupportValue( "Fishmongers", 1200, 0, true ),
      new SupportValue( "Furriers", 250, 0, true ),
      new SupportValue( "Glovemakers", 2400, 0, true ),
      new SupportValue( "Harness-makers", 2000, 0, true ),
      new SupportValue( "Hatmakers", 950, 0, true ),
      new SupportValue( "Hay Merchants", 2300, 0, true ),
      new SupportValue( "Illuminators", 3900, 0, true ),
      new SupportValue( "Inns", 2000, 0, true ),
      new SupportValue( "Jewelers", 400, 0, true ),
      new SupportValue( "Locksmiths", 1900, 0, true ),
      new SupportValue( "Magic Shops", 2800, 0, true ),
      new SupportValue( "Maidservants", 250, 0, true ),
      new SupportValue( "Masons", 500, 0, true ),
      new SupportValue( "Mercers", 700, 0, true ),
      new SupportValue( "Miners", 250, 0, false ),
      new SupportValue( "Old Clothes", 400, 0, true ),
      new SupportValue( "Painters", 1500, 0, true ),
      new SupportValue( "Pastrycooks", 500, 0, true ),
      new SupportValue( "Plasterers", 1400, 0, true ),
      new SupportValue( "Pursemakers", 1100, 0, true ),
      new SupportValue( "Roofers", 1800, 0, true ),
      new SupportValue( "Ropemakers", 1900, 0, true ),
      new SupportValue( "Rugmakers", 2000, 0, true ),
      new SupportValue( "Saddlers", 1000, 0, true ),
      new SupportValue( "Scabbardmakers", 850, 0, true ),
      new SupportValue( "Sculptors", 2000, 0, true ),
      new SupportValue( "Shoemakers", 150, 0, true ),
      new SupportValue( "Spice Merchants", 1400, 0, true ),
      new SupportValue( "Tailors", 250, 0, true ),
      new SupportValue( "Tanners", 2000, 0, true ),
      new SupportValue( "Taverns", 400, 0, true ),
      new SupportValue( "Watercarriers", 850, 0, true ),
      new SupportValue( "Weaponsmiths", 3000, 2, false ),
      new SupportValue( "Weavers", 600, 0, true ),
      new SupportValue( "Wine-sellers", 900, 0, true ),
      new SupportValue( "Woodcarvers", 2400, 0, true ),
      new SupportValue( "Woodsellers", 2400, 0, true )
  };
}
